version: "3.9"
services:
  app:
    image: document-llm
    build: .
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./src:/app   # Mounts the entire src directory
    container_name: nlp-dev
    env_file:
      - .env